.Dd $Mdocdate$
.Dt albertlertd 8
.Os OpenBSD 7.1
.Sh le cmene
.Nm albertlertd
.Nd le me'oi .cheesy. ke zmiku seljdesna me'oi .daemon. ke'e
.Sh la'oi .synopsis.
.Nm albertlertd
.Sh le velski
.No .ni'o ko'a goi la'o cmene.
.Nm albertlertd
.No .cmene cu pilno la'o cmene.
.Xr sysctl 8
.No .cmene le nu zgana ko'e goi le se ckaji be le skami poi se bajra
pe'a ko'a  .i ganai ko'a djice le du'u ko'e xlali gi jdesna ko'a
.Pp
.No .ni'o zbasu ko'e ki'u le nu la'o cmene.
.Ox 7.1
.No .cmene cu na jetnu tcidu le se rapydicysro be ko'i goi le
rapydicysro poi se vasru ko'e goi le selbeika'e skami be la .varik. gi'e
curmi lo nu xaksu ko'e ku noi rinka lo nu xaksu lo temci kei .e lo nu
snuti vimcu lo se zbasu  .i ko'a me'oi .cheesy. tcidu ko'e gi'e
fanta lo nu xaksu lo nu mulno xaksu ko'e
.Sh le datnyvei
.No .ni'o le sance be ko'a goi la'o cmene.
.Nm albertlertd
.No .cmene cu se vasru ko'e goi la'o datnyveiste.
.Pa /usr/local/share/albertlert
.No .datnyveiste  .i le tcidu cu kakne lo nu jmina le sance ko'e
.No .i ku'i la .varik. je'a darsygau fi lo nu pilno lo sance po
la'o samselkei.
.Em Deus Ex
.No .samselkei
.Pp
.No .ni'o le'i datnyvei poi ke'a goi ko'u zo'u racli fa lo nu klagau
ko'u ko'e cu vasru pe'a 
.Bl -tag -width Ds
.It la'o datnyvei. Pa OVERHEAT.WAV No .datnyvei noi ke'a goi ko'u zo'u
ganai ko'a jdice le du'u le skami cu me'oi .overheat. gi ko'u sance
ko'a ku'o .e
.It la'o datnyvei. Pa BATSIGNL.WAV No .datnyvei noi ke'a goi ko'u zo'u
jetnu fa le du'u ganai ko'a jdice le du'u naru'e xaksu pe'a le
rapydicysro gi ko'u sance ko'a kei .e le du'u le skami poi claxu lo
rapydicysro cu na se sance ko'u ku'o .e
.It la'o datnyvei. Pa OVERLOAD.WAV No .datnyvei noi ke'a goi ko'u zo'u
ganai ko'a jdice le du'u la'o gliban. load average .gliban po le
skami cu zmadu le'i rucyca'a po le skami gi ko'u sance ko'a
.El
.Sh la'oi .note.
.No ni'o la'o cmene.
.Nm albertlertd
.No .cmene cu me'oi .support. la'o cmene.
.Ox
.No .cmene po'o
.Sh le ciska
.No ni'o 
.An la .varik. .valefor.
noi na me'oi .programmer. gi'e terbe'i lo te benji be la'o
samymrijudri.
.Mt varikvalefor@aol.com
.No .samymrijudri .a la'o samymrijudri. @varikvalefor:matrix.org
.No .samymrijudri cu sampla la'o cmene.
.Nm albertlertd
.No .cmene
