.Dd $Mdocdate$
.Dt albertlertd 8
.Os OpenBSD 7.1
.Sh le cmene
.Nm albertlertd
.Nd le me'oi .cheesy. je ke zmiku seljdesna me'oi .daemon.
.Sh la'oi .synopsis.
.Nm albertlertd
.Sh le velski
.No ni'o ko'a goi la'o cmene.
.Nm albertlertd
.No .cmene cu pilno la'o cmene.
.Xr sysctl 8
.No .cmene lo nu zgana ko'e goi le se ckaji be le skami poi se bajra
pe'a ko'a  .i ganai ko'a djice le du'u ko'e xlali gi jdesna ko'a
.Pp
.No ni'o zbasu ko'e ki'u zo'e joi le su'u la'o cmene.
.Ox 7.1
.No .cmene cu jitfa jimpe pe'a fi le se rapydicysro be ko'i goi le
rapydicysro je se vasru ko'e goi le selbeika'e skami po la .varik. gi'e
curmi lo nu xaksu ko'e ku noi rinka lo nu xaksu lo temci kei .e lo nu
snuti vimcu lo se zbasu  .i ko'a me'oi .cheesy. tcidu ko'e gi'e
jai tolri'a lo nu xaksu lo nu mulno xaksu ko'e
.Sh le datnyvei
.No ni'o le sance be ko'a goi la'o cmene.
.Nm albertlertd
.No .cmene cu se vasru ko'e goi la'o datnyveiste.
.Pa /usr/local/share/albertlert
.No .datnyveiste  .i lo pilno cu kakne lo nu jmina pe'a lo sance ko'e
.No .i ku'i la .varik. cu je'a stidi lo nu pilno lo sance po
la'o samselkei.
.Em Deus Ex
.No .samselkei
.Pp
.No ni'o le'i datnyvei poi racli fa lo nu klagau ke'a ko'e cu vasru pe'a 
.Bl -tag -width Ds
.It la'o datnyvei. Pa OVERHEAT.WAV No .datnyvei noi
ganai ko'a jdice le du'u le skami cu me'oi .overheat. gi ke'a sance
ko'a ku'o .e
.It la'o datnyvei. Pa BATSIGNL.WAV No .datnyvei noi
jetnu fa le du'u ganai ko'a jdice le du'u naru'e xaksu pe'a le
rapydicysro gi ke'a sance ko'a kei .e le du'u le skami poi claxu lo
rapydicysro cu na se sance ke'a ku'o .e
.It la'o datnyvei. Pa OVERLOAD.WAV No .datnyvei noi
ganai ko'a jdice le du'u la'o gliban. load average .gliban po le
skami cu zmadu le'i rucyca'a po le skami gi ke'a sance ko'a
.El
.Sh zo'e je le cizra
.No ni'o troci zo'e naje lo nu la'o cmene.
.Nm albertlertd
.No .cmene cu mapti la'o cmene.
.Ox
.No .cmene
.Sh le ciska
.No ni'o 
.An la .varik. .VALefor.
noi ke'a ta'e sampla na gi'e terbe'i lo te benji be la'o
samymrijudri.
.Mt varikvalefor@aol.com
.No .samymrijudri .a la'o samymrijudri. @varikvalefor:matrix.org
.No .samymrijudri cu sampla la'o cmene.
.Nm albertlertd
.No .cmene
